// <auto-generated />
namespace EmplDataAcces.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MamaToSername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MamaToSername));
        
        string IMigrationMetadata.Id
        {
            get { return "201912251756432_MamaToSername"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
